{{ if .Values.instanceProfiles }}
{{- range .Values.instanceProfiles }}
---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: {{ .name }}
  {{- if and $.Release.IsInstall $.Values.cluster.create }}
  annotations:
    helm.sh/hook: "pre-install"
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  cpu: "{{ .cpu }}"
  memory: "{{ .memory }}"
{{- end }}
{{- end }}