{{ if .Values.configurations.create }}
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: {{ .Values.cluster.configurations.sgPostgresConfig }}
  {{- if and .Release.IsInstall .Values.cluster.create }}
  annotations:
    helm.sh/hook: "pre-install"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  postgresVersion: "{{ index (.Values.cluster.postgresVersion | splitList ".") 0 }}"
  {{- with (index .Values.configurations.postgresconfig "postgresql.conf") }}
  postgresql.conf:
  {{- range $key, $value := . }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
  {{- end }}
{{ end }}
