{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.repoCredentials }}
imagePullSecrets:
- name: {{ .Values.serviceAccount.repoCredentials }}
{{- end }}
{{- end }}